booksearch/pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

import testdb
from pybo import db
from pybo.forms import AnswerForm
# from pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now())
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('questions/question_detail.html', question=question, form=form)

booksearch/pybo/views/question_views.py
# from flask import Blueprint, render_template, request, url_for
# from werkzeug.utils import redirect
#
# import testdb
# from pybo import db
# from pybo.forms import QuestionForm, AnswerForm
# # from pybo.models import Question
# from datetime import datetime
# bp = Blueprint('question', __name__, url_prefix='/question')
#
#
# @bp.route('/list')
# def list_question():
#     page = request.args.get('page', type=int, default=1)  # 페이지
#     question_list = Question.query.order_by(Question.create_date.desc())
#     question_list = question_list.paginate(page, per_page=10)
#     return render_template('questions/question_list.html', question_list=question_list)
#
#
#
# @bp.route('/detail/<int:question_id>/')
# def detail(question_id):
#     question = Question.query.get_or_404(question_id)
#     form = AnswerForm()
#     return render_template('questions/question_detail.html', question=question,form=form)
#
# @bp.route('/create/',methods=('GET', 'POST'))
# def create():
#     print(request.method,1)
#     form = QuestionForm() # 새로운 객체? __init__에서 기억을 해두나? 초기화는 어디에서?
#     print(request.method,form.content.data,2)
#     if request.method == 'POST' and form.validate_on_submit():
#         question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
#         db.session.add(question)
#         db.session.commit()
#         return redirect(url_for('main.index'))
#     return render_template('questions/question_form.html', form=form)
#
# # @bp.route('/test')
# # def dbtest():
# #     testdb.getall_question()
# #     return '성공'
#
#

booksearch/pybo/templates/questions/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class = 'container my-3'></div>
{% if question %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card">
      <div class="card-header">
          {{ loop.index }}
      </div>
      <div class="card-body">
              <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
      </div>
    </div>
    {% endfor %}
<!--시간:{{question.create_date}}-->

{% endif %}
            <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
            {{ form.csrf_token }}
                <!-- 오류표시 Start -->
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field, errors in form.errors.items() %}
                    <strong>{{ form[field].label }}</strong>
                    <ul>
                        {% for error in errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endfor %}
                </div>
                {% endif %}
                <!-- 오류표시 End -->
                <div class="card">
                  <h5 class="card-header">구분선</h5>
                  <div class="card-body">
                    <h5 class="card-title">답변 입력해줘요</h5>
                    <textarea name="content" id="content" class="form-control" rows="10"></textarea>
                  <input type="submit" value="답변등록" class="btn btn-primary">
                  </div>
                </div>
            </form>
    </div>

{% endblock %}

booksearch/pybo/templates/questions/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10" value="{{ form.content.data or '' }}"></textarea >
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

booksearch/pybo/templates/questions/question_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr>
            <th class="table-active">번호</th>
            <th >제목</th>
            <th class="table-active">작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="table-danger">
            <td class="table-active text-white">{{ loop.index }}</td>
            <td >
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
            </td>
            <td class="table-active">{{ question.create_date.strftime('%Y-%m-%d|%H:%M') }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
<script>
$(document).ready(function() {

});
</script>
{% endblock %}