booksearch/pybo/views/search_views.py
from flask import Blueprint, render_template, request, url_for,g
from flask_wtf import form
from werkzeug.utils import redirect

import folium
import testdb
from pybo import db
from pybo.forms import QuestionForm, AnswerForm, BookRentForm
# from pybo.models import Question
from datetime import datetime
import pybo.libraryApi as lbApi
import random
from urllib import parse
from pybo.models import History

bp = Blueprint('search', __name__, url_prefix='/search')


@bp.route('/search')
def search():
    ranNum = random.randrange(1, 10)
    url = lbApi.url()
    bestSeller = lbApi.bestSeller(url)
    bookname= bestSeller['response']['docs'][ranNum]['doc']['bookname']
    return render_template('search/search.html', bestSeller=bookname)

@bp.route('/location/<int:isbn>/')
def location(isbn):
    print(isbn)
    lbInfo = lbApi.bookInLibrary(isbn)['response']['libs']
    print(lbInfo)
    bkDt = lbApi.bookSearch(isbn)['response']['detail'][0]['book']
    print(bkDt)
    return render_template('search/location.html', bookData=bkDt, lbInfo=lbInfo)

@bp.route('/list',methods=('GET', 'POST'))
def search_list():
    bookNm = request.form.get('bookNm')
    url = lbApi.url({'pageSize=20'})
    bestSeller = lbApi.bookSearchList(url, bookNm)
    return render_template('search/search_list.html', bookList=bestSeller['response']['docs'])


@bp.route('/booking', methods=('GET', ))
def booking_search():
    if g.user:
        bookname = request.args.get('bookname')
        print(bookname)
        isbn13= request.args.get('isbn13')
        print(isbn13)
        g.user.user_set.append(History(bookname=bookname, isbn13=isbn13))
        db.session.commit()
        return redirect(url_for('search.search'))
    else:
        return redirect(url_for('search.search'))

# @bp.route('/hide/<int:isbn>&<booknm>', methods=('GET',))
# def book_his(isbn,booknm):
#     history = History(bookname=booknm, isbn13=isbn) # 나중에 날짜도
#     db.session.add(history)
#     db.session.commit()
#     print('성공')
#     return redirect(url_for('search.search'))

booksearch/pybo/templates/search/location.html
{% extends 'base.html' %}
{% block content %}
<style>
.container {
	padding-top:50px;
}
.container2 {
	display: flex;
	/* display: inline-flex; */
	flex-direction: row;
    flex-wrap: wrap;

}
.item {
	margin-right: auto;
    margin-left: auto;
}

.map {
	width:50%;
	padding-top:30px;
	margin-right: auto;
    margin-left: auto;
}

.map img{
	width:100%;
	height:200px;
}
.bookImg {
	padding-left:30px;
}
.bookImg img {
	width:400px;
	height:250px;
	}
.bookData {
	width:40%;
}
</style>
<div class="container">
	{% if bookData %}
	<div class="container2">

		<div class="item bookImg"><img src="{{ bookData.bookImageURL}}"></div>
		<div class="item bookData"><h1>{{ bookData.bookname}} </h1>
			{{ bookData.description}}
		</div>
	</div>
	<div class="map my-3" style="" >
		<div id="map" style="width:600px;height:100%;"></div>
	</div>
	{% endif %}
</div>


<script>
$(document).ready(function() {
	var body = document.body,
	html = document.documentElement;
	var height = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );
	var height2 = $('html').height()
	$('.map').height(height-height2-2);
	function success({ coords, timestamp }) {
            const latitude = coords.latitude;   // 위도
            const longitude = coords.longitude; // 경도

	        kakaomap(latitude, longitude)
	};
 	function getUserLocation() {
            if (!navigator.geolocation) {
                throw "위치 정보가 지원되지 않습니다.";
            }
            navigator.geolocation.getCurrentPosition(success);
        }

        getUserLocation();
	function kakaomap(latitude, longitude){
		var container = document.getElementById('map');
		var options = {
			center: new kakao.maps.LatLng(latitude, longitude),
			level: 5
		};

		var map = new kakao.maps.Map(container, options);




		var positions = []
		{% if lbInfo %}
		{% for lb in lbInfo %}
			positions.push({'title':'{{lb['lib']['libName']}}'
			,content: '<div>{{lb['lib']['libName']}}</div>'
			,'latlng': new kakao.maps.LatLng({{lb['lib']['latitude']}}, {{lb['lib']['longitude']}})})
		{% endfor %}
		{% endif %}

// 마커 이미지의 이미지 주소입니다
var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

for (var i = 0; i < positions.length; i ++) {

    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(24, 35);

    // 마커 이미지를 생성합니다
    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: positions[i].latlng, // 마커를 표시할 위치
        title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage // 마커 이미지
    });
}
}

});
</script>
{% endblock %}

booksearch/pybo/templates/search/search.html
{% extends 'base.html' %}
{% block content %}
<style>
    @import url(https://fonts.googleapis.com/css?family=PT+Sans:400,700);


body{
	padding-top:-1px;
	height:100%;
    background: linear-gradient(90deg, #00c6ff 10%, #0072ff 90%);
	font-family: 'PT Sans', Helvetica, Arial, sans-serif;
}
h1 {
	text-shadow: 1px 1px 10px rgba(black, .5);
	padding-top:50px;
}

h1, h2 {
	text-align: center;
	color: white;
	font-size: 2.5em;
	line-height: 1.3em;
	font-weight: 300;
}

h2 {
	margin-top: 100px;
	font-size: 1.3em;
	font-style: italic;
	font-weight: 100;
}

.body {
	width: 100%;
	height: 250px;
	box-sizing: border-box;
}

input {
	box-sizing: border-box;
	font-size: 13px;
	vertical-align: top;
}

.wrapper {
	text-align: center;
	position: relative;
	height: 80px;
	font-size: 0;
	top: 50%;
	transform: translateY(-50%);
}

.search {
	padding: 0 30px;
	font-size: 18px;
	width: 60%;
	max-width: 400px;
	height: 80px;
	border: 1px solid darken(white, 30%);
	border-radius: 20px 0 0 20px;
}

.submit {
	cursor: pointer;
	border: none;
	background: url('http://thesuiteworld.com/wp-admin/maint/search-icon-white-png-540.png') no-repeat center center, #1E1E20;
	background-size: 35px 35px;
	border-radius: 0 20px 20px 0;
	padding: 15px 25px;
	display: inline-block;
	width: 150px;
	height: 80px;
}
</style>
<div class="container my-3">
   <div class="body">
	<h1> 도서관 책 검색</h1>
	<div class="wrapper">
		<form id="search-area" action="{{ url_for('search.search_list')}}" method="post">
			<input class="search" type="text" id="search" name="bookNm"/>
			<input class="submit" type="button" value=" " ><span class="text-white">검색</span> </input>
		</form>
	</div>
</div>
<!--    <h2>Click search to reset</h2>-->
</div>

<script>
$(document).ready(function() {
var ph = "{{bestSeller}}",
	searchBar = $('#search'),
	// placeholder loop counter
	phCount = 0;

// function to return random number between
// with min/max range
function randDelay(min, max) {
	return Math.floor(Math.random() * (max-min+1)+min);
}

// function to print placeholder text in a
// 'typing' effect
var arr
function printLetter(string, el) {
	// split string into character seperated array
	 arr = string.split(''),
		input = el,
		// store full placeholder
		origString = string,
		// get current placeholder value
		curPlace = $(input).attr("placeholder"),
		// append next letter to current placeholder
		placeholder = curPlace + arr[phCount];

	setTimeout(function(){
		console.log(phCount)
		// print placeholder text
		$(input).attr("placeholder", placeholder);
		// increase loop count
		phCount++;
		// run loop until placeholder is fully printed
		if (phCount < arr.length) {
			printLetter(origString, input);
		}
	// use random speed to simulate
	// 'human' typing
	}, randDelay(50, 90));
}

// function to init animation
function placeholder() {
	$(searchBar).attr("placeholder", "");
	printLetter(ph, searchBar);
}

placeholder();
$('.submit').click(function(e){
	if (phCount == arr.length) {
		var bookNm = $('#search').val() == '' ? $('#search').attr('placeholder') : $('#search').val()
		$('#search').val(bookNm);
		phCount = 0;

		$('#search-area').submit()
<!--		e.preventDefault();-->
<!--		placeholder();-->
	}
});
});
</script>
{% endblock %}

booksearch/pybo/templates/search/search_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr>
            <th class="table-active">번호</th>
            <th>제목</th>
            <th>작가</th>
            <th class="table-active">출판년</th>
            <th class="table-active">대출</th>
        </tr>
        </thead>
        <tbody>
        {% if bookList %}
        {% for book in bookList %}
        <tr class="table-danger test">
            <td class="table-active text-white">{{ loop.index }}
                <input class="isbn" type="hidden" readonly="readonly" value="{{book.doc.isbn}}">
            </td>
            <td >
                <a href="{{ url_for('search.location', isbn=book.doc.isbn13) }}">{{ book.doc.bookname }}</a>
            </td>
            <td class="table-active">{{book.doc.authors}}</td>
            <td class="table-active">{{book.doc.publication_year}}</td>
            <td class="table-active"><button class="btn btn-primary rent"><a class="text-white" href="/search/booking?bookname={{book.doc.bookname}}&isbn13={{book.doc.isbn13}}">대출</a>
<!-- 1.url_for('link',변수1=?,변수2)
     2. href=/?변수1=???&변수2=???
     3. 폼사용 근데 input이 없음-->
            </button></td>

        </tr>
        {% endfor %}
        {% elif recommend %}
        {% for temp in recommend %}
        <tr class="table-danger test">
            <td class="table-active text-white">{{ loop.index }}
                <input class="isbn" type="hidden" readonly="readonly" value="{{temp.bookisbn}}">
            </td>
            <td >
                <a href="{{ url_for('search.location', isbn=temp.bookisbn) }}">{{ temp.bookname }}</a>
            </td>
            <td class="table-active">{{temp.bookauthor}}</td>
            <td class="table-active">{{temp.bookyear}}</td>
            <td class="table-active"><button class="btn btn-primary rent"><a class="text-white" href="/recommend/booking?bookname={{temp.bookname}}&isbn13={{temp.isbn}}">대출</a>
            </button></td>

        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">책이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
<script>
$(document).ready(function() {
    $('.rent').click(function(){
        var index = $(this).closest('.test').find('.isbn').val();
        console.log(index)
    });
});
</script>
{% endblock %}